### REGISTER USER 
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
	"account": {
		"email": "test@nku.edu",
		"password": "test"
	},
	"profile": {
		"avatar": "https://i.imgur.com/wWbeuk9.jpg",
		"name": {
			"first": "test",
			"last": "test"
		},
		"username": "testone"
	}
}




